## What is Dataframe?
- Dataframe is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.
- Dataframe is a main object in Pandas. It is used to represent data with rows and columns (tabular or excel spreadsheet like data).

### Creating a dataframe

In [2]:
import pandas as pd
std_data = [
    (1,'vivek', 23, 'M'),
    (2,'rahul', 24, 'M'),
    (3,'sairaj', 23, 'M'),
    (4,'srijani', 23, 'F'),
]
df = pd.DataFrame(std_data)
print(df)

   0        1   2  3
0  1    vivek  23  M
1  2    rahul  24  M
2  3   sairaj  23  M
3  4  srijani  23  F

#### Creating an empty dataframe
- A basic DataFrame, which can be created is an Empty Dataframe.

In [3]:
# an empty dataframe
import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

**Reading a csv file**

In [4]:
import pandas as pd

std_data_file = '/Roadmap/sample data/student.csv'
df = pd.read_csv(std_data_file)
print(df)

    student_roll student_name  student_age  student_height
0              1         John           12             5.2
1              2        Smith           13             5.3
2              3        David           14             5.4
3              4         Mark           15             5.5
4              5         Paul           16             5.6
5              6        James           17             5.7
6              7       Andrew           18             5.8
7              8        Scott           19             5.9
8              9       Steven           20             6.0
9             10       Robert           21             6.1
10            11      William           22             6.2
11            12       Thomas           23             6.3
12            13       Donald           24             6.4
13            14       George           25             6.5
14            15      Kenneth           26             6.6
15            16       Edward           27             6.7
16            17        Jason           28             6.8
17            18       Ronald           29             6.9
18            19      Anthony           30             7.0
19            20        Kevin           31             7.1

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
print(df.head())

   student_roll student_name  student_age  student_height
0             1         John           12             5.2
1             2        Smith           13             5.3
2             3        David           14             5.4
3             4         Mark           15             5.5
4             5         Paul           16             5.6

In [7]:
print(df.tail())

    student_roll student_name  student_age  student_height
15            16       Edward           27             6.7
16            17        Jason           28             6.8
17            18       Ronald           29             6.9
18            19      Anthony           30             7.0
19            20        Kevin           31             7.1

In [8]:
print(df.shape)

(20, 4)

In [9]:
print(df.columns)

Index(['student_roll', 'student_name', 'student_age', 'student_height'], dtype='object')

In [10]:
print(df.dtypes)

student_roll        int64
student_name       object
student_age         int64
student_height    float64
dtype: object

In [11]:
df.student_age

0     12
1     13
2     14
3     15
4     16
5     17
6     18
7     19
8     20
9     21
10    22
11    23
12    24
13    25
14    26
15    27
16    28
17    29
18    30
19    31
Name: student_age, dtype: int64

In [12]:
df.student_height

0     5.2
1     5.3
2     5.4
3     5.5
4     5.6
5     5.7
6     5.8
7     5.9
8     6.0
9     6.1
10    6.2
11    6.3
12    6.4
13    6.5
14    6.6
15    6.7
16    6.8
17    6.9
18    7.0
19    7.1
Name: student_height, dtype: float64

In [13]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [14]:
df.values

array([[1, 'John', 12, 5.2],
       [2, 'Smith', 13, 5.3],
       [3, 'David', 14, 5.4],
       [4, 'Mark', 15, 5.5],
       [5, 'Paul', 16, 5.6],
       [6, 'James', 17, 5.7],
       [7, 'Andrew', 18, 5.8],
       [8, 'Scott', 19, 5.9],
       [9, 'Steven', 20, 6.0],
       [10, 'Robert', 21, 6.1],
       [11, 'William', 22, 6.2],
       [12, 'Thomas', 23, 6.3],
       [13, 'Donald', 24, 6.4],
       [14, 'George', 25, 6.5],
       [15, 'Kenneth', 26, 6.6],
       [16, 'Edward', 27, 6.7],
       [17, 'Jason', 28, 6.8],
       [18, 'Ronald', 29, 6.9],
       [19, 'Anthony', 30, 7.0],
       [20, 'Kevin', 31, 7.1]], dtype=object)

## **Operations on pandas dataframe**

In [1]:
import pandas as pd

df = pd.read_csv('/Roadmap/sample data/student.csv')

print(df)

    student_roll student_name  student_age  student_height
0              1         John           12             5.2
1              2        Smith           13             5.3
2              3        David           14             5.4
3              4         Mark           15             5.5
4              5         Paul           16             5.6
5              6        James           17             5.7
6              7       Andrew           18             5.8
7              8        Scott           19             5.9
8              9       Steven           20             6.0
9             10       Robert           21             6.1
10            11      William           22             6.2
11            12       Thomas           23             6.3
12            13       Donald           24             6.4
13            14       George           25             6.5
14            15      Kenneth           26             6.6
15            16       Edward           27             6.7
16            17        Jason           28             6.8
17            18       Ronald           29             6.9
18            19      Anthony           30             7.0
19            20        Kevin           31             7.1

**Selecting a column in pandas dataframe**

In [2]:
age = df['student_age']
print(age)

0     12
1     13
2     14
3     15
4     16
5     17
6     18
7     19
8     20
9     21
10    22
11    23
12    24
13    25
14    26
15    27
16    28
17    29
18    30
19    31
Name: student_age, dtype: int64

**Selecting a row in pandas dataframe**

In [3]:
row_1 = df.iloc[0]
print(row_1)

student_roll         1
student_name      John
student_age         12
student_height     5.2
Name: 0, dtype: object

**Selecting multiple rows in pandas dataframe**

In [5]:
df.iloc[[0,3]]

   student_roll student_name  student_age  student_height
0             1         John           12             5.2
3             4         Mark           15             5.5

In [6]:
df.iloc[[0,3], [0,1]]

   student_roll student_name
0             1         John
3             4         Mark

**Filtering in pandas dataframe**

In [8]:
df[df['student_age'] > 20]

    student_roll student_name  student_age  student_height
9             10       Robert           21             6.1
10            11      William           22             6.2
11            12       Thomas           23             6.3
12            13       Donald           24             6.4
13            14       George           25             6.5
14            15      Kenneth           26             6.6
15            16       Edward           27             6.7
16            17        Jason           28             6.8
17            18       Ronald           29             6.9
18            19      Anthony           30             7.0
19            20        Kevin           31             7.1

**Adding a new column to existing DataFrame in Pandas**

In [11]:
df['phone_numbers'] = [234567, 345678, 456789, 567890, 678901, 789012, 890123, 901234, 123456, 234567,23456,345678,56789,56768,57686,45678,56456,456789,567890,567689]

In [12]:
print(df)

    student_roll student_name  student_age  student_height  phone_numbers
0              1         John           12             5.2         234567
1              2        Smith           13             5.3         345678
2              3        David           14             5.4         456789
3              4         Mark           15             5.5         567890
4              5         Paul           16             5.6         678901
5              6        James           17             5.7         789012
6              7       Andrew           18             5.8         890123
7              8        Scott           19             5.9         901234
8              9       Steven           20             6.0         123456
9             10       Robert           21             6.1         234567
10            11      William           22             6.2          23456
11            12       Thomas           23             6.3         345678
12            13       Donald           24             6.4          56789
13            14       George           25             6.5          56768
14            15      Kenneth           26             6.6          57686
15            16       Edward           27             6.7          45678
16            17        Jason           28             6.8          56456
17            18       Ronald           29             6.9         456789
18            19      Anthony           30             7.0         567890
19            20        Kevin           31             7.1         567689

**Updating existing column of a DataFrame in Pandas**

In [17]:
df.loc[df.index == 0, 'student_name'] = 'vivek'

In [18]:
print(df)

    student_roll student_name  student_age  student_height  phone_numbers
0              1        vivek           12             5.2         234567
1              2        vivek           13             5.3         345678
2              3        David           14             5.4         456789
3              4         Mark           15             5.5         567890
4              5         Paul           16             5.6         678901
5              6        James           17             5.7         789012
6              7       Andrew           18             5.8         890123
7              8        Scott           19             5.9         901234
8              9       Steven           20             6.0         123456
9             10       Robert           21             6.1         234567
10            11      William           22             6.2          23456
11            12       Thomas           23             6.3         345678
12            13       Donald           24             6.4          56789
13            14       George           25             6.5          56768
14            15      Kenneth           26             6.6          57686
15            16       Edward           27             6.7          45678
16            17        Jason           28             6.8          56456
17            18       Ronald           29             6.9         456789
18            19      Anthony           30             7.0         567890
19            20        Kevin           31             7.1         567689